import TableView from "@/components/dashboard/ritase/TableView"
export default function page() {
  const dummyData = [
    {
      id: 1,
      phone: "081234567890",
      name: "Andi Setiawan",
      plate: "B 1234 ABC",
      type: "REGULER",
      pickup: "Cibinong",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 2,
      phone: "081234567891",
      name: "Rina Kartika",
      plate: "F 9876 DEF",
      type: "PREMIUM",
      pickup: "Dramaga",
      destination: "Jakarta",
      ss: "/profil.jpeg",
    },
    {
      id: 3,
      phone: "081234567892",
      name: "Dedi Mulyana",
      plate: "B 1122 XYZ",
      type: "REGULER",
      pickup: "Ciawi",
      destination: "Depok",
      ss: "/profil.jpeg",
    },
    {
      id: 4,
      phone: "081234567893",
      name: "Siti Lestari",
      plate: "F 4455 QWE",
      type: "PREMIUM",
      pickup: "Bogor",
      destination: "Cibubur",
      ss: "/profil.jpeg",
    },
    {
      id: 5,
      phone: "081234567894",
      name: "Agus Pratama",
      plate: "B 5566 RST",
      type: "REGULER",
      pickup: "Leuwiliang",
      destination: "Jakarta",
      ss: "/profil.jpeg",
    },
    {
      id: 6,
      phone: "081234567895",
      name: "Lina Marlina",
      plate: "B 7788 UIO",
      type: "PREMIUM",
      pickup: "Ciampea",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 7,
      phone: "081234567896",
      name: "Yudi Saputra",
      plate: "F 6677 TYU",
      type: "REGULER",
      pickup: "Citeureup",
      destination: "Cibinong",
      ss: "/profil.jpeg",
    },
    {
      id: 8,
      phone: "081234567897",
      name: "Mega Puspita",
      plate: "B 9988 VBN",
      type: "PREMIUM",
      pickup: "Gunung Putri",
      destination: "Bekasi",
      ss: "/profil.jpeg",
    },
    {
      id: 9,
      phone: "081234567898",
      name: "Rizki Hidayat",
      plate: "B 3322 JKL",
      type: "REGULER",
      pickup: "Ciseeng",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 10,
      phone: "081234567899",
      name: "Tina Anggraini",
      plate: "F 2244 ZXC",
      type: "PREMIUM",
      pickup: "Dramaga",
      destination: "Depok",
      ss: "/profil.jpeg",
    },
    {
      id: 11,
      phone: "081234567810",
      name: "Budi Hartono",
      plate: "B 1123 LMN",
      type: "REGULER",
      pickup: "Cibinong",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 12,
      phone: "081234567811",
      name: "Dina Amelia",
      plate: "F 9999 ASD",
      type: "PREMIUM",
      pickup: "Ciawi",
      destination: "Jakarta",
      ss: "/profil.jpeg",
    },
    {
      id: 13,
      phone: "081234567812",
      name: "Anton Wijaya",
      plate: "B 8877 POI",
      type: "REGULER",
      pickup: "Leuwiliang",
      destination: "Depok",
      ss: "/profil.jpeg",
    },
    {
      id: 14,
      phone: "081234567813",
      name: "Mira Andini",
      plate: "B 4455 RTY",
      type: "PREMIUM",
      pickup: "Bogor",
      destination: "Cibubur",
      ss: "/profil.jpeg",
    },
    {
      id: 15,
      phone: "081234567814",
      name: "Dani Firmansyah",
      plate: "F 7788 QAZ",
      type: "REGULER",
      pickup: "Ciampea",
      destination: "Jakarta",
      ss: "/profil.jpeg",
    },
    {
      id: 16,
      phone: "081234567815",
      name: "Rosa Melati",
      plate: "B 8899 WSX",
      type: "PREMIUM",
      pickup: "Citeureup",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 17,
      phone: "081234567816",
      name: "Surya Kurnia",
      plate: "B 5566 EDC",
      type: "REGULER",
      pickup: "Gunung Putri",
      destination: "Bekasi",
      ss: "/profil.jpeg",
    },
    {
      id: 18,
      phone: "081234567817",
      name: "Fitri Handayani",
      plate: "F 1122 RFV",
      type: "PREMIUM",
      pickup: "Ciseeng",
      destination: "Depok",
      ss: "/profil.jpeg",
    },
    {
      id: 19,
      phone: "081234567818",
      name: "Rahmat Hidayah",
      plate: "B 9988 TGB",
      type: "REGULER",
      pickup: "Cibinong",
      destination: "Bogor",
      ss: "/profil.jpeg",
    },
    {
      id: 20,
      phone: "081234567819",
      name: "Salsa Amelia",
      plate: "F 2233 YHN",
      type: "PREMIUM",
      pickup: "Dramaga",
      destination: "Jakarta",
      ss: "/profil.jpeg",
    },
  ]
  return (
    <div>
      <TableView data={dummyData} />
    </div>
  )
} 